let d1 = new Date();
let d2 = new Date();
let compare1 = d1 > d2;
console.log(compare1);
let compare2 = d1 < d2;
console.log(compare2);
let compare3 = d1 >= d2;
console.log(compare3);
let compare4 = d1 <= d2;
console.log(compare4);
let compare51 = d1 == d2;
console.log(compare51);
let compare5 = d1 === d2;
console.log(compare5);
let compare6 = d1 !== d2;
console.log(compare6);
let compare7 = d1.getTime() === d2.getTime();
console.log(compare7);
let compare8 = d1.getTime() !== d2.getTime();
console.log(compare8);
